version: '3'
services:
  gitea:
    image: gitea/arm
    restart: unless-stopped
    volumes: 
      - ./data/gitea:/data
    ports:
      - "3000:3000"
      - "2222:22"
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: unless-stopped
    ports: 
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ws12345678
      POSTGRES_USER: root
      POSTGRES_DB: gitea